### PR TITLE
Fix logging levels

### PR DESCRIPTION
**Pull request by Necior**

### CODE REVIEW

**Review by Necior — COMMENTED** [review]
There are 2 remaining invocations of `log::warn!` in `src/server.rs`.

Both of them have a comment saying that some scenario "should never happen". On the other hand, they just return `Ok(())`.

I find it somewhat confusing. Should these cases return some kind of a warning to the `task` user who tried to sync their database?

**Review by djmitche — COMMENTED** [review]
Can you give some hint as to the plan here? My thought was that these log messages showed up to let the user know the server was running.

**Comment by Necior** [comment]
As of right now, only logs at the level `error` are logged. Therefore, users don't see any of these warnings anyway (by default).

I suppose that if someone is familiar with logging enough to choose a custom logging level (e.g. by setting `RUST_LOG`), they would find logging a purely informational thing (server started, it's serving on that port) as a warning confusing.

But maybe it's just me :)

So, the proposed plan is: print `info` or higher logs by default. Use `info` when it's actually an informational log.

I expressed my thoughts on logging in https://github.com/GothenburgBitFactory/taskchampion-sync-server/issues/27#issuecomment-2241359103. If we can agree on what the logging should look like in this project, I'm happy to send a few small PRs.

**Review by djmitche — APPROVED** [review]
Ah, thanks -- I hadn't read #27 yet.

I appreciate your careful thought about this!

**Pull request merged**
